export const countries = {
	AFG: { flagUrl: "flags/af.svg", emoji: "🇦🇫", name: "Afghanistan" },
	ALB: { flagUrl: "flags/al.svg", emoji: "🇦🇱", name: "Albania" },
	ALG: { flagUrl: "flags/dz.svg", emoji: "🇩🇿", name: "Algeria" },
	AND: { flagUrl: "flags/ad.svg", emoji: "🇦🇩", name: "Andorra" },
	AGO: { flagUrl: "flags/ao.svg", emoji: "🇦🇴", name: "Angola" },
	ANT: { flagUrl: "flags/ag.svg", emoji: "🇦🇬", name: "Antigua & Barbuda" },
	ARG: { flagUrl: "flags/ar.svg", emoji: "🇦🇷", name: "Argentina" },
	ARM: { flagUrl: "flags/am.svg", emoji: "🇦🇲", name: "Armenia" },
	ARU: { flagUrl: "flags/aw.svg", emoji: "🇦🇼", name: "Aruba" },
	AUS: { flagUrl: "flags/au.svg", emoji: "🇦🇺", name: "Australia" },
	AUT: { flagUrl: "flags/at.svg", emoji: "🇦🇹", name: "Austria" },
	AZE: { flagUrl: "flags/az.svg", emoji: "🇦🇿", name: "Azerbaijan" },
	BAH: { flagUrl: "flags/bs.svg", emoji: "🇧🇸", name: "Bahamas" },
	BRN: { flagUrl: "flags/bh.svg", emoji: "🇧🇭", name: "Bahrain" },
	BAN: { flagUrl: "flags/bd.svg", emoji: "🇧🇩", name: "Bangladesh" },
	BAR: { flagUrl: "flags/bb.svg", emoji: "🇧🇧", name: "Barbados" },
	BLR: { flagUrl: "flags/by.svg", emoji: "🏳️", name: "Belarus" },
	BEL: { flagUrl: "flags/be.svg", emoji: "🇧🇪", name: "Belgium" },
	BLZ: { flagUrl: "flags/bz.svg", emoji: "🇧🇿", name: "Belize" },
	BEN: { flagUrl: "flags/bj.svg", emoji: "🇧🇯", name: "Benin" },
	BER: { flagUrl: "flags/bm.svg", emoji: "🇧🇲", name: "Bermuda" },
	BHU: { flagUrl: "flags/bt.svg", emoji: "🇧🇹", name: "Bhutan" },
	BOL: { flagUrl: "flags/bo.svg", emoji: "🇧🇴", name: "Bolivia" },
	BIH: { flagUrl: "flags/ba.svg", emoji: "🇧🇦", name: "Bosnia & Herzegovina" },
	BOT: { flagUrl: "flags/bw.svg", emoji: "🇧🇼", name: "Botswana" },
	BRA: { flagUrl: "flags/br.svg", emoji: "🇧🇷", name: "Brazil" },
	IVB: { flagUrl: "flags/vg.svg", emoji: "🇻🇬", name: "British Virgin Islands" },
	BRU: { flagUrl: "flags/bn.svg", emoji: "🇧🇳", name: "Brunei Darussalam" },
	BUL: { flagUrl: "flags/bg.svg", emoji: "🇧🇬", name: "Bulgaria" },
	BUR: { flagUrl: "flags/bi.svg", emoji: "🇧🇮", name: "Burundi" },
	BDI: { flagUrl: "flags/bi.svg", emoji: "🇧🇮", name: "Burundi" },
	CAM: { flagUrl: "flags/kh.svg", emoji: "🇰🇭", name: "Cambodia" },
	CMR: { flagUrl: "flags/cm.svg", emoji: "🇨🇲", name: "Cameroon" },
	CAN: { flagUrl: "flags/ca.svg", emoji: "🇨🇦", name: "Canada" },
	CPV: { flagUrl: "flags/cv.svg", emoji: "🇨🇻", name: "Cape Verde" },
	CAY: { flagUrl: "flags/ky.svg", emoji: "🇰🇾", name: "Cayman Islands" },
	CAF: {
		flagUrl: "flags/cf.svg",
		emoji: "🇨🇫",
		name: "Central African Republic",
	},
	TCH: { flagUrl: "flags/td.svg", emoji: "🇹🇩", name: "Chad" },
	CHI: { flagUrl: "flags/cl.svg", emoji: "🇨🇱", name: "Chile" },
	CHN: { flagUrl: "flags/cn.svg", emoji: "🇨🇳", name: "China" },
	COL: { flagUrl: "flags/co.svg", emoji: "🇨🇴", name: "Colombia" },
	COM: { flagUrl: "flags/km.svg", emoji: "🇰🇲", name: "Comoros" },
	CGO: { flagUrl: "flags/cg.svg", emoji: "🇨🇬", name: "Congo" },
	COD: { flagUrl: "flags/cd.svg", emoji: "🇨🇩", name: "Congo, Democratic Republic" },
	COK: { flagUrl: "flags/ck.svg", emoji: "🇨🇰", name: "Cook Islands" },
	CRC: { flagUrl: "flags/cr.svg", emoji: "🇨🇷", name: "Costa Rica" },
	CIV: { flagUrl: "flags/ci.svg", emoji: "🇨🇮", name: "Côte d'Ivoire" },
	CRO: { flagUrl: "flags/hr.svg", emoji: "🇭🇷", name: "Croatia" },
	CUB: { flagUrl: "flags/cu.svg", emoji: "🇨🇺", name: "Cuba" },
	CYP: { flagUrl: "flags/cy.svg", emoji: "🇨🇾", name: "Cyprus" },
	CZE: { flagUrl: "flags/cz.svg", emoji: "🇨🇿", name: "Czech Republic" },
	DEN: { flagUrl: "flags/dk.svg", emoji: "🇩🇰", name: "Denmark" },
	DJI: { flagUrl: "flags/dj.svg", emoji: "🇩🇯", name: "Djibouti" },
	DMA: { flagUrl: "flags/dm.svg", emoji: "🇩🇲", name: "Dominica" },
	DOM: { flagUrl: "flags/do.svg", emoji: "🇩🇴", name: "Dominican Republic" },
	ECU: { flagUrl: "flags/ec.svg", emoji: "🇪🇨", name: "Ecuador" },
	EGY: { flagUrl: "flags/eg.svg", emoji: "🇪🇬", name: "Egypt" },
	ESA: { flagUrl: "flags/sv.svg", emoji: "🇸🇻", name: "El Salvador" },
	GEQ: { flagUrl: "flags/gq.svg", emoji: "🇬🇶", name: "Equatorial Guinea" },
	ERI: { flagUrl: "flags/er.svg", emoji: "🇪🇷", name: "Eritrea" },
	EST: { flagUrl: "flags/ee.svg", emoji: "🇪🇪", name: "Estonia" },
	ESW: { flagUrl: "flags/sz.svg", emoji: "🇸🇿", name: "Eswatini" },
	ETH: { flagUrl: "flags/et.svg", emoji: "🇪🇹", name: "Ethiopia" },
	FAR: { flagUrl: "flags/fo.svg", emoji: "🇫🇴", name: "Faroe Islands" },
	FIJ: { flagUrl: "flags/fj.svg", emoji: "🇫🇯", name: "Fiji" },
	FIN: { flagUrl: "flags/fi.svg", emoji: "🇫🇮", name: "Finland" },
	FRA: { flagUrl: "flags/fr.svg", emoji: "🇫🇷", name: "France" },
	GAB: { flagUrl: "flags/ga.svg", emoji: "🇬🇦", name: "Gabon" },
	GAM: { flagUrl: "flags/gm.svg", emoji: "🇬🇲", name: "Gambia" },
	GEO: { flagUrl: "flags/ge.svg", emoji: "🇬🇪", name: "Georgia" },
	GER: { flagUrl: "flags/de.svg", emoji: "🇩🇪", name: "Germany" },
	GHA: { flagUrl: "flags/gh.svg", emoji: "🇬🇭", name: "Ghana" },
	GRE: { flagUrl: "flags/gr.svg", emoji: "🇬🇷", name: "Greece" },
	GRN: { flagUrl: "flags/gd.svg", emoji: "🇬🇩", name: "Grenada" },
	GUM: { flagUrl: "flags/gu.svg", emoji: "🇬🇺", name: "Guam" },
	GUA: { flagUrl: "flags/gt.svg", emoji: "🇬🇹", name: "Guatemala" },
	GUI: { flagUrl: "flags/gn.svg", emoji: "🇬🇳", name: "Guinea" },
	GBR: { flagUrl: "flags/gb.svg", emoji: "🇬🇧", name: "Great Britain" },
	GBS: { flagUrl: "flags/gw.svg", emoji: "🇬🇼", name: "Guinea-Bissau" },
	GUY: { flagUrl: "flags/gy.svg", emoji: "🇬🇾", name: "Guyana" },
	HAI: { flagUrl: "flags/ht.svg", emoji: "🇭🇹", name: "Haiti" },
	HON: { flagUrl: "flags/hn.svg", emoji: "🇭🇳", name: "Honduras" },
	HKG: { flagUrl: "flags/hk.svg", emoji: "🇭🇰", name: "Hong Kong" },
	HUN: { flagUrl: "flags/hu.svg", emoji: "🇭🇺", name: "Hungary" },
	ISL: { flagUrl: "flags/is.svg", emoji: "🇮🇸", name: "Iceland" },
	IND: { flagUrl: "flags/in.svg", emoji: "🇮🇳", name: "India" },
	INA: { flagUrl: "flags/id.svg", emoji: "🇮🇩", name: "Indonesia" },
	IRI: { flagUrl: "flags/ir.svg", emoji: "🇮🇷", name: "Iran" },
	IRQ: { flagUrl: "flags/iq.svg", emoji: "🇮🇶", name: "Iraq" },
	IRL: { flagUrl: "flags/ie.svg", emoji: "🇮🇪", name: "Ireland" },
	ISR: { flagUrl: "flags/il.svg", emoji: "🇮🇱", name: "Israel" },
	ITA: { flagUrl: "flags/it.svg", emoji: "🇮🇹", name: "Italy" },
	JAM: { flagUrl: "flags/jm.svg", emoji: "🇯🇲", name: "Jamaica" },
	JPN: { flagUrl: "flags/jp.svg", emoji: "🇯🇵", name: "Japan" },
	JOR: { flagUrl: "flags/jo.svg", emoji: "🇯🇴", name: "Jordan" },
	KAZ: { flagUrl: "flags/kz.svg", emoji: "🇰🇿", name: "Kazakhstan" },
	KEN: { flagUrl: "flags/ke.svg", emoji: "🇰🇪", name: "Kenya" },
	PRK: {
		flagUrl: "flags/kp.svg",
		emoji: "🇰🇵",
		name: "Korea, Democratic People's Republic",
	},
	KOR: { flagUrl: "flags/kr.svg", emoji: "🇰🇷", name: "Korea, Republic of" },
	KUW: { flagUrl: "flags/kw.svg", emoji: "🇰🇼", name: "Kuwait" },
	KGZ: { flagUrl: "flags/kg.svg", emoji: "🇰🇬", name: "Kyrgyzstan" },
	LAO: { flagUrl: "flags/la.svg", emoji: "🇱🇦", name: "Laos" },
	LAT: { flagUrl: "flags/lv.svg", emoji: "🇱🇻", name: "Latvia" },
	LBN: { flagUrl: "flags/lb.svg", emoji: "🇱🇧", name: "Lebanon" },
	LBR: { flagUrl: "flags/lr.svg", emoji: "🇱🇷", name: "Liberia" },
	LBA: { flagUrl: "flags/ly.svg", emoji: "🇱🇾", name: "Libya" },
	LIE: { flagUrl: "flags/li.svg", emoji: "🇱🇮", name: "Liechtenstein" },
	LTU: { flagUrl: "flags/lt.svg", emoji: "🇱🇹", name: "Lithuania" },
	LUX: { flagUrl: "flags/lu.svg", emoji: "🇱🇺", name: "Luxembourg" },
	MAC: { flagUrl: "flags/mo.svg", emoji: "🇲🇴", name: "Macao" },
	MAD: { flagUrl: "flags/mg.svg", emoji: "🇲🇬", name: "Madagascar" },
	MAW: { flagUrl: "flags/mw.svg", emoji: "🇲🇼", name: "Malawi" },
	MAS: { flagUrl: "flags/my.svg", emoji: "🇲🇾", name: "Malaysia" },
	MDV: { flagUrl: "flags/mv.svg", emoji: "🇲🇻", name: "Maldives" },
	MLI: { flagUrl: "flags/ml.svg", emoji: "🇲🇱", name: "Mali" },
	MLT: { flagUrl: "flags/mt.svg", emoji: "🇲🇹", name: "Malta" },
	MHL: { flagUrl: "flags/mh.svg", emoji: "🇲🇭", name: "Marshall Islands" },
	MTN: { flagUrl: "flags/mr.svg", emoji: "🇲🇷", name: "Mauritania" },
	MRI: { flagUrl: "flags/mu.svg", emoji: "🇲🇺", name: "Mauritius" },
	MEX: { flagUrl: "flags/mx.svg", emoji: "🇲🇽", name: "Mexico" },
	FSM: { flagUrl: "flags/fm.svg", emoji: "🇫🇲", name: "Micronesia" },
	MDA: { flagUrl: "flags/md.svg", emoji: "🇲🇩", name: "Moldova" },
	MON: { flagUrl: "flags/mc.svg", emoji: "🇲🇨", name: "Monaco" },
	MGL: { flagUrl: "flags/mn.svg", emoji: "🇲🇳", name: "Mongolia" },
	MNE: { flagUrl: "flags/me.svg", emoji: "🇲🇪", name: "Montenegro" },
	MAR: { flagUrl: "flags/ma.svg", emoji: "🇲🇦", name: "Morocco" },
	MOZ: { flagUrl: "flags/mz.svg", emoji: "🇲🇿", name: "Mozambique" },
	MYA: { flagUrl: "flags/mm.svg", emoji: "🇲🇲", name: "Myanmar" },
	NAM: { flagUrl: "flags/na.svg", emoji: "🇳🇦", name: "Namibia" },
	NMI: {
		flagUrl: "flags/mp.svg",
		emoji: "🇲🇵",
		name: "Northern Mariana Islands",
	},
	NRU: { flagUrl: "flags/nr.svg", emoji: "🇳🇷", name: "Nauru" },
	NEP: { flagUrl: "flags/np.svg", emoji: "🇳🇵", name: "Nepal" },
	NED: { flagUrl: "flags/nl.svg", emoji: "🇳🇱", name: "Netherlands" },
	AHO: { flagUrl: "flags/nl.svg", emoji: "🇳🇱", name: "Netherlands Antilles" },
	NZL: { flagUrl: "flags/nz.svg", emoji: "🇳🇿", name: "New Zealand" },
	NCA: { flagUrl: "flags/ni.svg", emoji: "🇳🇮", name: "Nicaragua" },
	NIG: { flagUrl: "flags/ne.svg", emoji: "🇳🇪", name: "Niger" },
	NGR: { flagUrl: "flags/ng.svg", emoji: "🇳🇬", name: "Nigeria" },
	NIR: { flagUrl: "flags/gb-nir.svg", emoji: "🇬🇧", name: "Northern Ireland" },
	MKD: { flagUrl: "flags/mk.svg", emoji: "🇲🇰", name: "North Macedonia" },
	NOR: { flagUrl: "flags/no.svg", emoji: "🇳🇴", name: "Norway" },
	OMA: { flagUrl: "flags/om.svg", emoji: "🇴🇲", name: "Oman" },
	PAK: { flagUrl: "flags/pk.svg", emoji: "🇵🇰", name: "Pakistan" },
	PLW: { flagUrl: "flags/pw.svg", emoji: "🇵🇼", name: "Palau" },
	PLE: { flagUrl: "flags/ps.svg", emoji: "🇵🇸", name: "Palestine" },
	PAN: { flagUrl: "flags/pa.svg", emoji: "🇵🇦", name: "Panama" },
	PNG: { flagUrl: "flags/pg.svg", emoji: "🇵🇬", name: "Papua New Guinea" },
	PAR: { flagUrl: "flags/py.svg", emoji: "🇵🇾", name: "Paraguay" },
	PER: { flagUrl: "flags/pe.svg", emoji: "🇵🇪", name: "Peru" },
	PHI: { flagUrl: "flags/ph.svg", emoji: "🇵🇭", name: "Philippines" },
	POL: { flagUrl: "flags/pl.svg", emoji: "🇵🇱", name: "Poland" },
	POR: { flagUrl: "flags/pt.svg", emoji: "🇵🇹", name: "Portugal" },
	PUR: { flagUrl: "flags/pr.svg", emoji: "🇵🇷", name: "Puerto Rico" },
	QAT: { flagUrl: "flags/qa.svg", emoji: "🇶🇦", name: "Qatar" },
	ROU: { flagUrl: "flags/ro.svg", emoji: "🇷🇴", name: "Romania" },
	RUS: { flagUrl: "flags/ru.svg", emoji: "🏳️", name: "Russia" },
	RWA: { flagUrl: "flags/rw.svg", emoji: "🇷🇼", name: "Rwanda" },
	SKN: { flagUrl: "flags/kn.svg", emoji: "🇰🇳", name: "Saint Kitts & Nevis" },
	LCA: { flagUrl: "flags/lc.svg", emoji: "🇱🇨", name: "Saint Lucia" },
	VIN: {
		flagUrl: "flags/vc.svg",
		emoji: "🇻🇨",
		name: "Saint Vincent & the Grenadines",
	},
	SAM: { flagUrl: "flags/ws.svg", emoji: "🇼🇸", name: "Samoa" },
	SMR: { flagUrl: "flags/sm.svg", emoji: "🇸🇲", name: "San Marino" },
	STP: { flagUrl: "flags/st.svg", emoji: "🇸🇹", name: "São Tomé & Príncipe" },
	KSA: { flagUrl: "flags/sa.svg", emoji: "🇸🇦", name: "Saudi Arabia" },
	SEN: { flagUrl: "flags/sn.svg", emoji: "🇸🇳", name: "Senegal" },
	SRB: { flagUrl: "flags/rs.svg", emoji: "🇷🇸", name: "Serbia" },
	SEY: { flagUrl: "flags/sc.svg", emoji: "🇸🇨", name: "Seychelles" },
	SLE: { flagUrl: "flags/sl.svg", emoji: "🇸🇱", name: "Sierra Leone" },
	SIN: { flagUrl: "flags/sg.svg", emoji: "🇸🇬", name: "Singapore" },
	SVK: { flagUrl: "flags/sk.svg", emoji: "🇸🇰", name: "Slovakia" },
	SLO: { flagUrl: "flags/si.svg", emoji: "🇸🇮", name: "Slovenia" },
	SOL: { flagUrl: "flags/sb.svg", emoji: "🇸🇧", name: "Solomon Islands" },
	SOM: { flagUrl: "flags/so.svg", emoji: "🇸🇴", name: "Somalia" },
	RSA: { flagUrl: "flags/za.svg", emoji: "🇿🇦", name: "South Africa" },
	SSD: { flagUrl: "flags/ss.svg", emoji: "🇸🇸", name: "South Sudan" },
	ESP: { flagUrl: "flags/es.svg", emoji: "🇪🇸", name: "Spain" },
	SRI: { flagUrl: "flags/lk.svg", emoji: "🇱🇰", name: "Sri Lanka" },
	SDN: { flagUrl: "flags/sd.svg", emoji: "🇸🇩", name: "Sudan" },
	SUR: { flagUrl: "flags/sr.svg", emoji: "🇸🇷", name: "Suriname" },
	SWE: { flagUrl: "flags/se.svg", emoji: "🇸🇪", name: "Sweden" },
	SUI: { flagUrl: "flags/ch.svg", emoji: "🇨🇭", name: "Switzerland" },
	SYR: { flagUrl: "flags/sy.svg", emoji: "🇸🇾", name: "Syria" },
	TPE: { flagUrl: "flags/tw.svg", emoji: "🇹🇼", name: "Taiwan" },
	TJK: { flagUrl: "flags/tj.svg", emoji: "🇹🇯", name: "Tajikistan" },
	TAN: { flagUrl: "flags/tz.svg", emoji: "🇹🇿", name: "Tanzania" },
	THA: { flagUrl: "flags/th.svg", emoji: "🇹🇭", name: "Thailand" },
	TLS: { flagUrl: "flags/tl.svg", emoji: "🇹🇱", name: "Timor-Leste" },
	TOG: { flagUrl: "flags/tg.svg", emoji: "🇹🇬", name: "Togo" },
	TGA: { flagUrl: "flags/to.svg", emoji: "🇹🇴", name: "Tonga" },
	TTO: { flagUrl: "flags/tt.svg", emoji: "🇹🇹", name: "Trinidad & Tobago" },
	TUN: { flagUrl: "flags/tn.svg", emoji: "🇹🇳", name: "Tunisia" },
	TUR: { flagUrl: "flags/tr.svg", emoji: "🇹🇷", name: "Turkey" },
	TKM: { flagUrl: "flags/tm.svg", emoji: "🇹🇲", name: "Turkmenistan" },
	TCA: {
		flagUrl: "flags/tc.svg",
		emoji: "🇹🇨",
		name: "Turks & Caicos Islands",
	},
	TUV: { flagUrl: "flags/tv.svg", emoji: "🇹🇻", name: "Tuvalu" },
	TWN: { flagUrl: "flags/tw.svg", emoji: "🇹🇼", name: "Taiwan" },
	UGA: { flagUrl: "flags/ug.svg", emoji: "🇺🇬", name: "Uganda" },
	UKR: { flagUrl: "flags/ua.svg", emoji: "🇺🇦", name: "Ukraine" },
	UAE: { flagUrl: "flags/ae.svg", emoji: "🇦🇪", name: "United Arab Emirates" },
	USA: { flagUrl: "flags/us.svg", emoji: "🇺🇸", name: "United States" },
	URU: { flagUrl: "flags/uy.svg", emoji: "🇺🇾", name: "Uruguay" },
	UZB: { flagUrl: "flags/uz.svg", emoji: "🇺🇿", name: "Uzbekistan" },
	VAN: { flagUrl: "flags/vu.svg", emoji: "🇻🇺", name: "Vanuatu" },
	VEN: { flagUrl: "flags/ve.svg", emoji: "🇻🇪", name: "Venezuela" },
	VIE: { flagUrl: "flags/vn.svg", emoji: "🇻🇳", name: "Vietnam" },
	ISV: { flagUrl: "flags/vi.svg", emoji: "🇻🇮", name: "Virgin Islands, US" },
	YEM: { flagUrl: "flags/ye.svg", emoji: "🇾🇪", name: "Yemen" },
	ZAM: { flagUrl: "flags/zm.svg", emoji: "🇿🇲", name: "Zambia" },
	ZIM: { flagUrl: "flags/zw.svg", emoji: "🇿🇼", name: "Zimbabwe" },
};
