export const countries = {
	AFG: { flagUrl: "flags/afghanistan.svg", emoji: "🇦🇫", name: "Afghanistan" },
	ALB: { flagUrl: "flags/albania.svg", emoji: "🇦🇱", name: "Albania" },
	ALG: { flagUrl: "flags/algeria.svg", emoji: "🇩🇿", name: "Algeria" },
	AND: { flagUrl: "flags/andorra.svg", emoji: "🇦🇩", name: "Andorra" },
	AGO: { flagUrl: "flags/angola.svg", emoji: "🇦🇴", name: "Angola" },
	ANT: { flagUrl: "flags/antigua-and-barbuda.svg", emoji: "🇦🇬", name: "Antigua & Barbuda" },
	ARG: { flagUrl: "flags/argentina.svg", emoji: "🇦🇷", name: "Argentina" },
	ARM: { flagUrl: "flags/armenia.svg", emoji: "🇦🇲", name: "Armenia" },
	ARU: { flagUrl: "flags/aruba.svg", emoji: "🇦🇼", name: "Aruba" },
	AUS: { flagUrl: "flags/australia.svg", emoji: "🇦🇺", name: "Australia" },
	AUT: { flagUrl: "flags/austria.svg", emoji: "🇦🇹", name: "Austria" },
	AZE: { flagUrl: "flags/azerbaijan.svg", emoji: "🇦🇿", name: "Azerbaijan" },
	BAH: { flagUrl: "flags/bahamas.svg", emoji: "🇧🇸", name: "Bahamas" },
	BRN: { flagUrl: "flags/bahrain.svg", emoji: "🇧🇭", name: "Bahrain" },
	BAN: { flagUrl: "flags/bangladesh.svg", emoji: "🇧🇩", name: "Bangladesh" },
	BAR: { flagUrl: "flags/barbados.svg", emoji: "🇧🇧", name: "Barbados" },
	BLR: { flagUrl: "flags/belarus.svg", emoji: "🏳️", name: "Belarus" },
	BEL: { flagUrl: "flags/belgium.svg", emoji: "🇧🇪", name: "Belgium" },
	BLZ: { flagUrl: "flags/belize.svg", emoji: "🇧🇿", name: "Belize" },
	BEN: { flagUrl: "flags/benin.svg", emoji: "🇧🇯", name: "Benin" },
	BER: { flagUrl: "flags/bermuda.svg", emoji: "🇧🇲", name: "Bermuda" },
	BHU: { flagUrl: "flags/bhutan.svg", emoji: "🇧🇹", name: "Bhutan" },
	BOL: { flagUrl: "flags/bolivia.svg", emoji: "🇧🇴", name: "Bolivia" },
	BIH: { flagUrl: "flags/bosnia.svg", emoji: "🇧🇦", name: "Bosnia & Herzegovina" },
	BOT: { flagUrl: "flags/botswana.svg", emoji: "🇧🇼", name: "Botswana" },
	BRA: { flagUrl: "flags/brazil.svg", emoji: "🇧🇷", name: "Brazil" },
	IVB: { flagUrl: "flags/british-virgin-islands.svg", emoji: "🇻🇬", name: "British Virgin Islands" },
	BRU: { flagUrl: "flags/brunei.svg", emoji: "🇧🇳", name: "Brunei Darussalam" },
	BUL: { flagUrl: "flags/bulgaria.svg", emoji: "🇧🇬", name: "Bulgaria" },
	BUR: { flagUrl: "flags/burundi.svg", emoji: "🇧🇮", name: "Burundi" },
	BDI: { flagUrl: "flags/burundi.svg", emoji: "🇧🇮", name: "Burundi" },
	CAM: { flagUrl: "flags/cambodia.svg", emoji: "🇰🇭", name: "Cambodia" },
	CMR: { flagUrl: "flags/cameroon.svg", emoji: "🇨🇲", name: "Cameroon" },
	CAN: { flagUrl: "flags/canada.svg", emoji: "🇨🇦", name: "Canada" },
	CPV: { flagUrl: "flags/cape-verde.svg", emoji: "🇨🇻", name: "Cape Verde" },
	CAY: { flagUrl: "flags/cayman-islands.svg", emoji: "🇰🇾", name: "Cayman Islands" },
	CAF: {
		flagUrl: "flags/central-african-republic.svg",
		emoji: "🇨🇫",
		name: "Central African Republic",
	},
	TCH: { flagUrl: "flags/chad.svg", emoji: "🇹🇩", name: "Chad" },
	CHI: { flagUrl: "flags/chile.svg", emoji: "🇨🇱", name: "Chile" },
	CHN: { flagUrl: "flags/china.svg", emoji: "🇨🇳", name: "China" },
	COL: { flagUrl: "flags/colombia.svg", emoji: "🇨🇴", name: "Colombia" },
	COM: { flagUrl: "flags/comoros.svg", emoji: "🇰🇲", name: "Comoros" },
	CGO: { flagUrl: "flags/congo.svg", emoji: "🇨🇬", name: "Congo" },
	COD: { flagUrl: "flags/congo-democratic.svg", emoji: "🇨🇩", name: "Congo, Democratic Republic" },
	COK: { flagUrl: "flags/cook-islands.svg", emoji: "🇨🇰", name: "Cook Islands" },
	CRC: { flagUrl: "flags/costa-rica.svg", emoji: "🇨🇷", name: "Costa Rica" },
	CIV: { flagUrl: "flags/ivory-coast.svg", emoji: "🇨🇮", name: "Côte d'Ivoire" },
	CRO: { flagUrl: "flags/croatia.svg", emoji: "🇭🇷", name: "Croatia" },
	CUB: { flagUrl: "flags/cuba.svg", emoji: "🇨🇺", name: "Cuba" },
	CYP: { flagUrl: "flags/cyprus.svg", emoji: "🇨🇾", name: "Cyprus" },
	CZE: { flagUrl: "flags/czech-republic.svg", emoji: "🇨🇿", name: "Czech Republic" },
	DEN: { flagUrl: "flags/denmark.svg", emoji: "🇩🇰", name: "Denmark" },
	DJI: { flagUrl: "flags/djibouti.svg", emoji: "🇩🇯", name: "Djibouti" },
	DMA: { flagUrl: "flags/dominica.svg", emoji: "🇩🇲", name: "Dominica" },
	DOM: { flagUrl: "flags/dominican-republic.svg", emoji: "🇩🇴", name: "Dominican Republic" },
	ECU: { flagUrl: "flags/ecuador.svg", emoji: "🇪🇨", name: "Ecuador" },
	EGY: { flagUrl: "flags/egypt.svg", emoji: "🇪🇬", name: "Egypt" },
	ESA: { flagUrl: "flags/el-salvador.svg", emoji: "🇸🇻", name: "El Salvador" },
	GEQ: { flagUrl: "flags/equatorial-guinea.svg", emoji: "🇬🇶", name: "Equatorial Guinea" },
	ERI: { flagUrl: "flags/eritrea.svg", emoji: "🇪🇷", name: "Eritrea" },
	EST: { flagUrl: "flags/estonia.svg", emoji: "🇪🇪", name: "Estonia" },
	ESW: { flagUrl: "flags/eswatini.svg", emoji: "🇸🇿", name: "Eswatini" },
	ETH: { flagUrl: "flags/ethiopia.svg", emoji: "🇪🇹", name: "Ethiopia" },
	FAR: { flagUrl: "flags/faroe-islands.svg", emoji: "🇫🇴", name: "Faroe Islands" },
	FIJ: { flagUrl: "flags/fiji.svg", emoji: "🇫🇯", name: "Fiji" },
	FIN: { flagUrl: "flags/finland.svg", emoji: "🇫🇮", name: "Finland" },
	FRA: { flagUrl: "flags/france.svg", emoji: "🇫🇷", name: "France" },
	GAB: { flagUrl: "flags/gabon.svg", emoji: "🇬🇦", name: "Gabon" },
	GAM: { flagUrl: "flags/gambia.svg", emoji: "🇬🇲", name: "Gambia" },
	GEO: { flagUrl: "flags/georgia.svg", emoji: "🇬🇪", name: "Georgia" },
	GER: { flagUrl: "flags/germany.svg", emoji: "🇩🇪", name: "Germany" },
	GHA: { flagUrl: "flags/ghana.svg", emoji: "🇬🇭", name: "Ghana" },
	GRE: { flagUrl: "flags/greece.svg", emoji: "🇬🇷", name: "Greece" },
	GRN: { flagUrl: "flags/grenada.svg", emoji: "🇬🇩", name: "Grenada" },
	GUM: { flagUrl: "flags/guam.svg", emoji: "🇬🇺", name: "Guam" },
	GUA: { flagUrl: "flags/guatemala.svg", emoji: "🇬🇹", name: "Guatemala" },
	GUI: { flagUrl: "flags/guinea.svg", emoji: "🇬🇳", name: "Guinea" },
	GBR: { flagUrl: "flags/united-kingdom.svg", emoji: "🇬🇧", name: "Great Britain" },
	GBS: { flagUrl: "flags/guinea.svg", emoji: "🇬🇼", name: "Guinea-Bissau" },
	GUY: { flagUrl: "flags/guyana.svg", emoji: "🇬🇾", name: "Guyana" },
	HAI: { flagUrl: "flags/haiti.svg", emoji: "🇭🇹", name: "Haiti" },
	HON: { flagUrl: "flags/honduras.svg", emoji: "🇭🇳", name: "Honduras" },
	HKG: { flagUrl: "flags/hong-kong.svg", emoji: "🇭🇰", name: "Hong Kong" },
	HUN: { flagUrl: "flags/hungary.svg", emoji: "🇭🇺", name: "Hungary" },
	ISL: { flagUrl: "flags/iceland.svg", emoji: "🇮🇸", name: "Iceland" },
	IND: { flagUrl: "flags/india.svg", emoji: "🇮🇳", name: "India" },
	INA: { flagUrl: "flags/indonesia.svg", emoji: "🇮🇩", name: "Indonesia" },
	IRI: { flagUrl: "flags/iran.svg", emoji: "🇮🇷", name: "Iran" },
	IRQ: { flagUrl: "flags/iraq.svg", emoji: "🇮🇶", name: "Iraq" },
	IRL: { flagUrl: "flags/ireland.svg", emoji: "🇮🇪", name: "Ireland" },
	ISR: { flagUrl: "flags/israel.svg", emoji: "🇮🇱", name: "Israel" },
	ITA: { flagUrl: "flags/italy.svg", emoji: "🇮🇹", name: "Italy" },
	JAM: { flagUrl: "flags/jamaica.svg", emoji: "🇯🇲", name: "Jamaica" },
	JPN: { flagUrl: "flags/japan.svg", emoji: "🇯🇵", name: "Japan" },
	JOR: { flagUrl: "flags/jordan.svg", emoji: "🇯🇴", name: "Jordan" },
	KAZ: { flagUrl: "flags/kazakhstan.svg", emoji: "🇰🇿", name: "Kazakhstan" },
	KEN: { flagUrl: "flags/kenya.svg", emoji: "🇰🇪", name: "Kenya" },
	PRK: {
		flagUrl: "flags/north-korea.svg",
		emoji: "🇰🇵",
		name: "Korea, Democratic People's Republic",
	},
	KOR: { flagUrl: "flags/south-korea.svg", emoji: "🇰🇷", name: "Korea, Republic of" },
	KUW: { flagUrl: "flags/kuwait.svg", emoji: "🇰🇼", name: "Kuwait" },
	KGZ: { flagUrl: "flags/kyrgyzstan.svg", emoji: "🇰🇬", name: "Kyrgyzstan" },
	LAO: { flagUrl: "flags/laos.svg", emoji: "🇱🇦", name: "Laos" },
	LAT: { flagUrl: "flags/latvia.svg", emoji: "🇱🇻", name: "Latvia" },
	LBN: { flagUrl: "flags/lebanon.svg", emoji: "🇱🇧", name: "Lebanon" },
	LBR: { flagUrl: "flags/liberia.svg", emoji: "🇱🇷", name: "Liberia" },
	LBA: { flagUrl: "flags/libya.svg", emoji: "🇱🇾", name: "Libya" },
	LIE: { flagUrl: "flags/liechtenstein.svg", emoji: "🇱🇮", name: "Liechtenstein" },
	LTU: { flagUrl: "flags/lithuania.svg", emoji: "🇱🇹", name: "Lithuania" },
	LUX: { flagUrl: "flags/luxembourg.svg", emoji: "🇱🇺", name: "Luxembourg" },
	MAC: { flagUrl: "flags/macao.svg", emoji: "🇲🇴", name: "Macao" },
	MAD: { flagUrl: "flags/madagascar.svg", emoji: "🇲🇬", name: "Madagascar" },
	MAW: { flagUrl: "flags/malawi.svg", emoji: "🇲🇼", name: "Malawi" },
	MAS: { flagUrl: "flags/malaysia.svg", emoji: "🇲🇾", name: "Malaysia" },
	MDV: { flagUrl: "flags/maldives.svg", emoji: "🇲🇻", name: "Maldives" },
	MLI: { flagUrl: "flags/mali.svg", emoji: "🇲🇱", name: "Mali" },
	MLT: { flagUrl: "flags/malta.svg", emoji: "🇲🇹", name: "Malta" },
	MHL: { flagUrl: "flags/marshall-islands.svg", emoji: "🇲🇭", name: "Marshall Islands" },
	MTN: { flagUrl: "flags/mauritania.svg", emoji: "🇲🇷", name: "Mauritania" },
	MRI: { flagUrl: "flags/mauritius.svg", emoji: "🇲🇺", name: "Mauritius" },
	MEX: { flagUrl: "flags/mexico.svg", emoji: "🇲🇽", name: "Mexico" },
	FSM: { flagUrl: "flags/micronesia.svg", emoji: "🇫🇲", name: "Micronesia" },
	MDA: { flagUrl: "flags/moldova.svg", emoji: "🇲🇩", name: "Moldova" },
	MON: { flagUrl: "flags/monaco.svg", emoji: "🇲🇨", name: "Monaco" },
	MGL: { flagUrl: "flags/mongolia.svg", emoji: "🇲🇳", name: "Mongolia" },
	MNE: { flagUrl: "flags/montenegro.svg", emoji: "🇲🇪", name: "Montenegro" },
	MAR: { flagUrl: "flags/morocco.svg", emoji: "🇲🇦", name: "Morocco" },
	MOZ: { flagUrl: "flags/mozambique.svg", emoji: "🇲🇿", name: "Mozambique" },
	MYA: { flagUrl: "flags/myanmar.svg", emoji: "🇲🇲", name: "Myanmar" },
	NAM: { flagUrl: "flags/namibia.svg", emoji: "🇳🇦", name: "Namibia" },
	NMI: {
		flagUrl: "flags/northern-mariana-islands.svg",
		emoji: "🇲🇵",
		name: "Northern Mariana Islands",
	},
	NRU: { flagUrl: "flags/nauru.svg", emoji: "🇳🇷", name: "Nauru" },
	NEP: { flagUrl: "flags/nepal.svg", emoji: "🇳🇵", name: "Nepal" },
	NED: { flagUrl: "flags/netherlands.svg", emoji: "🇳🇱", name: "Netherlands" },
	AHO: { flagUrl: "flags/netherlands.svg", emoji: "🇳🇱", name: "Netherlands Antilles" },
	NZL: { flagUrl: "flags/new-zealand.svg", emoji: "🇳🇿", name: "New Zealand" },
	NCA: { flagUrl: "flags/nicaragua.svg", emoji: "🇳🇮", name: "Nicaragua" },
	NIG: { flagUrl: "flags/niger.svg", emoji: "🇳🇪", name: "Niger" },
	NGR: { flagUrl: "flags/nigeria.svg", emoji: "🇳🇬", name: "Nigeria" },
	NIR: { flagUrl: "flags/united-kingdom.svg", emoji: "🇬🇧", name: "Northern Ireland" },
	MKD: { flagUrl: "flags/north-macedonia.svg", emoji: "🇲🇰", name: "North Macedonia" },
	NOR: { flagUrl: "flags/norway.svg", emoji: "🇳🇴", name: "Norway" },
	OMA: { flagUrl: "flags/oman.svg", emoji: "🇴🇲", name: "Oman" },
	PAK: { flagUrl: "flags/pakistan.svg", emoji: "🇵🇰", name: "Pakistan" },
	PLW: { flagUrl: "flags/palau.svg", emoji: "🇵🇼", name: "Palau" },
	PLE: { flagUrl: "flags/palestine.svg", emoji: "🇵🇸", name: "Palestine" },
	PAN: { flagUrl: "flags/panama.svg", emoji: "🇵🇦", name: "Panama" },
	PNG: { flagUrl: "flags/papua-new-guinea.svg", emoji: "🇵🇬", name: "Papua New Guinea" },
	PAR: { flagUrl: "flags/paraguay.svg", emoji: "🇵🇾", name: "Paraguay" },
	PER: { flagUrl: "flags/peru.svg", emoji: "🇵🇪", name: "Peru" },
	PHI: { flagUrl: "flags/philippines.svg", emoji: "🇵🇭", name: "Philippines" },
	POL: { flagUrl: "flags/poland.svg", emoji: "🇵🇱", name: "Poland" },
	POR: { flagUrl: "flags/portugal.svg", emoji: "🇵🇹", name: "Portugal" },
	PUR: { flagUrl: "flags/puerto-rico.svg", emoji: "🇵🇷", name: "Puerto Rico" },
	QAT: { flagUrl: "flags/qatar.svg", emoji: "🇶🇦", name: "Qatar" },
	ROU: { flagUrl: "flags/romania.svg", emoji: "🇷🇴", name: "Romania" },
	RUS: { flagUrl: "flags/russia.svg", emoji: "🏳️", name: "Russia" },
	RWA: { flagUrl: "flags/rwanda.svg", emoji: "🇷🇼", name: "Rwanda" },
	SKN: { flagUrl: "flags/saint-kitts-and-nevis.svg", emoji: "🇰🇳", name: "Saint Kitts & Nevis" },
	LCA: { flagUrl: "flags/saint-lucia.svg", emoji: "🇱🇨", name: "Saint Lucia" },
	VIN: {
		flagUrl: "flags/saint-vincent-and-the-grenadines.svg",
		emoji: "🇻🇨",
		name: "Saint Vincent & the Grenadines",
	},
	SAM: { flagUrl: "flags/samoa.svg", emoji: "🇼🇸", name: "Samoa" },
	SMR: { flagUrl: "flags/san-marino.svg", emoji: "🇸🇲", name: "San Marino" },
	STP: { flagUrl: "flags/so-tom-and-prncipe.svg", emoji: "🇸🇹", name: "São Tomé & Príncipe" },
	KSA: { flagUrl: "flags/saudi-arabia.svg", emoji: "🇸🇦", name: "Saudi Arabia" },
	SEN: { flagUrl: "flags/senegal.svg", emoji: "🇸🇳", name: "Senegal" },
	SRB: { flagUrl: "flags/serbia.svg", emoji: "🇷🇸", name: "Serbia" },
	SEY: { flagUrl: "flags/seychelles.svg", emoji: "🇸🇨", name: "Seychelles" },
	SLE: { flagUrl: "flags/sierra-leone.svg", emoji: "🇸🇱", name: "Sierra Leone" },
	SIN: { flagUrl: "flags/singapore.svg", emoji: "🇸🇬", name: "Singapore" },
	SVK: { flagUrl: "flags/slovakia.svg", emoji: "🇸🇰", name: "Slovakia" },
	SLO: { flagUrl: "flags/slovenia.svg", emoji: "🇸🇮", name: "Slovenia" },
	SOL: { flagUrl: "flags/solomon-islands.svg", emoji: "🇸🇧", name: "Solomon Islands" },
	SOM: { flagUrl: "flags/somalia.svg", emoji: "🇸🇴", name: "Somalia" },
	RSA: { flagUrl: "flags/south-africa.svg", emoji: "🇿🇦", name: "South Africa" },
	SSD: { flagUrl: "flags/south-sudan.svg", emoji: "🇸🇸", name: "South Sudan" },
	ESP: { flagUrl: "flags/spain.svg", emoji: "🇪🇸", name: "Spain" },
	SRI: { flagUrl: "flags/sri-lanka.svg", emoji: "🇱🇰", name: "Sri Lanka" },
	SDN: { flagUrl: "flags/sudan.svg", emoji: "🇸🇩", name: "Sudan" },
	SUR: { flagUrl: "flags/suriname.svg", emoji: "🇸🇷", name: "Suriname" },
	SWE: { flagUrl: "flags/sweden.svg", emoji: "🇸🇪", name: "Sweden" },
	SUI: { flagUrl: "flags/switzerland.svg", emoji: "🇨🇭", name: "Switzerland" },
	SYR: { flagUrl: "flags/syria.svg", emoji: "🇸🇾", name: "Syria" },
	TPE: { flagUrl: "flags/taiwan.svg", emoji: "🇹🇼", name: "Taiwan" },
	TJK: { flagUrl: "flags/tajikistan.svg", emoji: "🇹🇯", name: "Tajikistan" },
	TAN: { flagUrl: "flags/tanzania.svg", emoji: "🇹🇿", name: "Tanzania" },
	THA: { flagUrl: "flags/thailand.svg", emoji: "🇹🇭", name: "Thailand" },
	TLS: { flagUrl: "flags/east-timor.svg", emoji: "🇹🇱", name: "Timor-Leste" },
	TOG: { flagUrl: "flags/togo.svg", emoji: "🇹🇬", name: "Togo" },
	TGA: { flagUrl: "flags/tonga.svg", emoji: "🇹🇴", name: "Tonga" },
	TTO: { flagUrl: "flags/trinidad-and-tobago.svg", emoji: "🇹🇹", name: "Trinidad & Tobago" },
	TUN: { flagUrl: "flags/tunisia.svg", emoji: "🇹🇳", name: "Tunisia" },
	TUR: { flagUrl: "flags/turkey.svg", emoji: "🇹🇷", name: "Turkey" },
	TKM: { flagUrl: "flags/turkmenistan.svg", emoji: "🇹🇲", name: "Turkmenistan" },
	TCA: {
		flagUrl: "flags/turks-and-caicos-islands.svg",
		emoji: "🇹🇨",
		name: "Turks & Caicos Islands",
	},
	TUV: { flagUrl: "flags/tuvalu.svg", emoji: "🇹🇻", name: "Tuvalu" },
	TWN: { flagUrl: "flags/taiwan.svg", emoji: "🇹🇼", name: "Taiwan" },
	UGA: { flagUrl: "flags/uganda.svg", emoji: "🇺🇬", name: "Uganda" },
	UKR: { flagUrl: "flags/ukraine.svg", emoji: "🇺🇦", name: "Ukraine" },
	UAE: { flagUrl: "flags/united-arab-emirates.svg", emoji: "🇦🇪", name: "United Arab Emirates" },
	USA: { flagUrl: "flags/united-states.svg", emoji: "🇺🇸", name: "United States" },
	URU: { flagUrl: "flags/uruguay.svg", emoji: "🇺🇾", name: "Uruguay" },
	UZB: { flagUrl: "flags/uzbekistan.svg", emoji: "🇺🇿", name: "Uzbekistan" },
	VAN: { flagUrl: "flags/vanuatu.svg", emoji: "🇻🇺", name: "Vanuatu" },
	VEN: { flagUrl: "flags/venezuela.svg", emoji: "🇻🇪", name: "Venezuela" },
	VIE: { flagUrl: "flags/vietnam.svg", emoji: "🇻🇳", name: "Vietnam" },
	ISV: { flagUrl: "flags/virgin-islands.svg", emoji: "🇻🇮", name: "Virgin Islands, US" },
	YEM: { flagUrl: "flags/yemen.svg", emoji: "🇾🇪", name: "Yemen" },
	ZAM: { flagUrl: "flags/zambia.svg", emoji: "🇿🇲", name: "Zambia" },
	ZIM: { flagUrl: "flags/zimbabwe.svg", emoji: "🇿🇼", name: "Zimbabwe" },
};

// ARU: { flagUrl: "", emoji: "🇦🇼", name: "Aruba" },
// BER: { flagUrl: "", emoji: "🇧🇲", name: "Bermuda" },
// IVB: { flagUrl: "", emoji: "🇻🇬", name: "British Virgin Islands" },
// CAY: { flagUrl: "", emoji: "🇰🇾", name: "Cayman Islands" },
// FAR: { flagUrl: "", emoji: "🇫🇴", name: "Faroe Islands" },
// GUM: { flagUrl: "", emoji: "🇬🇺", name: "Guam" },
// HKG: { flagUrl: "", emoji: "🇭🇰", name: "Hong Kong" },
// NMI: { flagUrl: "", emoji: "🇲🇵", name: "Northern Mariana Islands" },
// NIR: { flagUrl: "", emoji: "🇬🇧", name: "Northern Ireland" },
// PUR: { flagUrl: "", emoji: "🇵🇷", name: "Puerto Rico" },
// STP: { flagUrl: "", emoji: "🇸🇹", name: "São Tomé & Príncipe" },
// TCA: { flagUrl: "", emoji: "🇹🇨", name: "Turks & Caicos Islands" },
// ISV: { flagUrl: "", emoji: "🇻🇮", name: "Virgin Islands, US" },
